### PR TITLE
Cleanup and Coding Standards

### PR DESCRIPTION
**Pull request by simplechris**
Hey Zach,

Awesome job so far on the 2.0 branch, we're really liking it.

Whilst debugging some issues over the past few days, I started to notice a few inconsistencies in the code in regard to documentation and formatting etc, so I've spent some time cleaning up the project :)

I've performed the following tasks to clean-up and make the more consistent and (hopefully) easier to understand:

- Applied a consistent coding standard to fix some inconsistencies in indentation/whitespace/brace positioning etc [ https://github.com/simplechris/elasticsearch-php/commit/bcf2ae92a99ec7e096398b6fdba85834b352c446 ]
- Removed commented out or 'dead' code. [ https://github.com/simplechris/elasticsearch-php/commit/f41f1c050d0e097b95f0eee3f6641e55bec4b371, https://github.com/simplechris/elasticsearch-php/commit/3d0709485a3f34b945e228c9ed900d7629e9c66d]
- Removed the sporadic IDE added comments from the tops of some files [ https://github.com/simplechris/elasticsearch-php/commit/783f3208b0c42f230366c6c478ff8e802f373a25 ]
- Removed any unused  `use` statements of classes that are no longer used within the file [ https://github.com/simplechris/elasticsearch-php/commit/049ea0062666f00e9e5716b867e2d04bf67c5917 ]
- Gone through and added any missing docblocks to classes and methods that were missing them. [ https://github.com/simplechris/elasticsearch-php/commit/a5b29331bd4063e1ba2ef1c811c429c6f6b38136 ]
- a few other misc cleanup operations.

If you're not keen on any particular change, then that's cool - just let me know and I'll rebase it away. I can go back and squash a few of the commits too, and write better commit messages if you'd like.

Thanks dude!

### CODE REVIEW

**Comment by polyfractal** [comment]
Oh wow, this is great!  Thanks!

I don't think I'll have time to look through this until the end of the week (or perhaps over the weekend), but from a high level all the changes sound good...I don't expect anything in there I won't like.

We should probably codify some of these in the CONTRIBUTING doc too, just so that it's official and we can encourage future PRs to follow the same standard (and to prevent me from being lazy too :) )

**Comment by simplechris** [comment]
Sure, over the weekend I'll add something to the `CONTRIBUTING.md` file, and also squash these commits down a bit :+1:

**Comment by polyfractal** [comment]
Skimmed over these on my flight, it all looks great to me!  I'm not overly concerned about a "clean commit history", so don't feel like you have to go crazy squashing.

**Comment by simplechris** [comment]
- [x]  squash similar commits
- [x]  add step to `CONTRIBUTING.md` about applying coding standards.
- [ ] rebase in recent changes from `2.0` branch

**Comment by simplechris** [comment]
@polyfractal - I've rebased again to include the changes from [`2.0`](https://github.com/elastic/elasticsearch-php/tree/2.0) that got merged in today, so this PR will merge cleanly again now :+1:

**Comment by polyfractal** [comment]
emot-toot

Merging!

**Pull request merged**
