### PR TITLE
Added Table of contents to Readme

### PR DESCRIPTION
**Pull request by naneri**

### CODE REVIEW

**Comment by philkra** [comment]
@naneri could you please sign the [CLA](https://www.elastic.co/contributor-agreement)?

**Comment by naneri** [comment]
Done

**Comment by naneri** [comment]
How do I pass it with the commit?

**Comment by philkra** [comment]
> How do I pass it with the commit?

You don't have to, the "checks" already picked the signed CLA up.

**Comment by philkra** [comment]
thank you for you contribution!

**Pull request merged**
