### PR TITLE
Re-Add the DeleteByQuery Functionality

### LINKED ISSUE #512: _delete_by_query support missing
### Summary of problem or feature request

The library is missing support for the [delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) api.

The actual endpoint named `DeleteByQuery` was removed [here](https://github.com/elastic/elasticsearch-php/commit/9f3776a), but the code doesn't seem to have any relationship to the API documented in the link above.

### System details

- Operating System: n/a
- PHP Version: 5.6/7.0
- ES-PHP client version: 5.0
- Elasticsearch version: 5.1

### PR DESCRIPTION
**Pull request by chrisguitarguy**
Closes #512 

Reverts 9f3776a224ef4c65e75df7d004ee37361f64567f and brings the `DeleteByQuery` endpoint up to spec with the current API.

I don't think this is actually covered by tests anywhere?

Addionally, I'm unsure about whether or not I've caught all the allowed params. There are a [whole mess of them](https://github.com/elastic/elasticsearch/blob/v5.1.1/rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json) in the API spec, but some seem like generic settings. As it is, I grabbed the params from [the delete by query docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html).

### CODE REVIEW

**Comment by polyfractal** [comment]
Awesome, thanks for doing this!  I've been snowed under with other projects lately and have been putting this off.

The list of [params in the spec](https://github.com/elastic/elasticsearch/blob/v5.1.1/rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json#L20-L163) that you linked are indeed the correct set of params.  The docs are unfortunately built from the php doc block comments at the top of each namespace method, which are currently maintained by hand (they used to be automated, broke, hasn't been fixed yet because generally changes are slow and not a big deal).

So if you want, you can add the params.  If not I'll merge and add the params myself.  Up to you!

Thanks again :)

**Comment by polyfractal** [comment]
Oh and tests would be covered by the YAML integration tests, although currently Core hasn't ported the tests back.  They'll be added at some point, at which the runner on our side will start testing it against a cluster again. :)

**Comment by chrisguitarguy** [comment]
> So if you want, you can add the params. 

@polyfractal Added! I just grabbed the delete by query spec json and did a little scripting.

Do I need to worry about the text failures here? Looks like [master was failing before](https://travis-ci.org/elastic/elasticsearch-php/builds/179793876)?

**Comment by chrisguitarguy** [comment]
Any updates here @polyfractal? Do you need anything more from me?

**Comment by polyfractal** [comment]
Hey sorry, busy week.  Gonna get to this today :)

No need to worry about the test failures, Travis is broken right now (it doesn't like a JSON option, and I haven't figured out how to update it's version of jsonc yet)

**Comment by polyfractal** [comment]
Tested, looks good.  Thanks!

**Comment by chrisguitarguy** [comment]
Any chance of getting a bugfix release with this functionality in 5.x, @polyfractal ?

**Comment by polyfractal** [comment]
Sure, I'll cut a release today. :) 

It'll have to be a minor version bump though, since it's a "new" feature. So `v5.1.0`

**Comment by polyfractal** [comment]
Sorry for the delay... just tagged `v5.1.0` :)

**Pull request merged**
