### PR TITLE
Allow psr/log v3

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
I did sign the CLA

**Comment by ruudk** [comment]
@technige What do you think?

**Comment by franmomu** [comment]
Looks like https://github.com/elastic/elasticsearch-php/blob/6d77eb5f69878fda0f7347ee2f937e1662063008/src/Elasticsearch/Common/EmptyLogger.php is implemeting `LoggerInterface`, so I guess a return type should be added there (maybe acceptable BC break)

**Comment by technige** [comment]
@ruudk Just adding a quick acknowledgement that I've seen this, and I'll get back to you soon.

**Comment by technige** [comment]
To follow up, we have now added this to our internal TODO list for review.

cc: @ezimuel

**Comment by technige** [comment]
See also the separate changes proposed in #1190.

**Comment by franmomu** [comment]
@ruudk I've tried to make a PR to your branch but it didn't appear on Github UI 🤔 you can copy the changes done in https://github.com/elastic/elasticsearch-php/pull/1190 and I think the targeted branch should be 7.17

**Comment by ruudk** [comment]
@technige @franmomu Rebased the PR, targeting 7.17, pulling in #1190. Please approve workflow

**Comment by vince83110** [comment]
Just because I am french and annoying, +1 for this one, I tested the PR on my side and thanks for the work, all of you!

**Comment by ezimuel** [comment]
Thanks @ruudk for this PR, I'm going to release it in `v7.17.0`.

**Pull request merged**
