### PR TITLE
[DOCS] Add ES|QL doc structure

### PR DESCRIPTION
**Pull request by marciw**
Adds an `esql.asciidoc` file that sets up a basic structure for the ES|QL documentation. Based on @szabosteve's Java client docs PR ([#789](https://github.com/elastic/elasticsearch-java/pull/789/files)).

This includes adding a folder structure for `helpers` instead of keeping the docs all on one page (but we can undo that).

@ezimuel This needs expanding and tailoring for the PHP client (it's really just placeholder text from the Java client docs). All other feedback is welcome, especially because I'm still so new to Elastic and to the client docs.

[Preview](https://elasticsearch-php_bk_1403.docs-preview.app.elstc.co/guide/en/elasticsearch/client/php-api/master/esql.html)

### CODE REVIEW

**Comment by ezimuel** [comment]
@marciw sorry for the late reply. I need to adapt the context to the PHP client using the approach that I blogged [here](https://www.elastic.co/search-labs/blog/esql-php-map-object-class).

**Comment by marciw** [comment]
> @marciw sorry for the late reply. I need to adapt the context to the PHP client using the approach that I blogged [here](https://www.elastic.co/search-labs/blog/esql-php-map-object-class).

@ezimuel Ah, great! I'm sure it will take me longer than it would you, but if you like, I can put together a skeleton/notes or just take a crack at adapting it and you can expand...?

**Comment by ezimuel** [comment]
@marciw I adapted the context for PHP with some examples. Let me know what do you think, thanks!

**Comment by marciw** [comment]
> @marciw I adapted the context for PHP with some examples. Let me know what do you think, thanks!

@ezimuel  I did a [minor edit](https://github.com/elastic/elasticsearch-php/pull/1403/commits/f56baeaa77773008a937c792d8445e965634954b) -- take a look when you can and feel free to veto my changes. Thanks again for writing this up! 🏆

**Review by ezimuel — APPROVED** [review]
LGTM!

**Pull request merged**
