### PR TITLE
Replace Sami by Doctum and fix .gitignore

### PR DESCRIPTION
**Pull request by williamdes**
- Replace Sami by Doctum (11264c63bb09bdd7cb11b30f6bc57578a6f66471)
- fix .gitignore (da6895d18b4020032f55f7e967d5c97390f0cecd)
- Update built docs (df6d17b4c3f816510dc1997054eca853ae94288b)

I hope I used the right branch because I was unsure with just a quick look to you GIT history

### CODE REVIEW

**Comment by ezimuel** [comment]
Thanks @williamdes, I'm not familiar with Doctum, I just saw it's a fork of Sami. I'll review this asap.

**Comment by williamdes** [comment]
> Thanks @williamdes, I'm not familiar with Doctum, I just saw it's a fork of Sami. I'll review this asap.

Hi @ezimuel 
Did you have some time to have a look ?

**Comment by williamdes** [comment]
Hi @ezimuel 
It seems like the notification was lost somewhere ;)

**Comment by ezimuel** [comment]
I'm sorry @williamdes for the delay. Can you send the PR against `7.x` branch instead of `master`? Thanks!

**Comment by williamdes** [comment]
> I'm sorry @williamdes for the delay. Can you send the PR against `7.x` branch instead of `master`? Thanks!

Hi @ezimuel 
I did trick the history and cherry-pick my commits + re-built the documentation

How will you handle master branch ?

**Comment by ezimuel** [comment]
@williamdes the`master` branch is the next 8.0.0 version of `elasticsearch-php` that will be ready when Elasticsearch 8 will be available, next year. We need to release in pair with Elasticsearch version. That's why we are using 7.x branch at the moment as current branch. More information are available here: https://github.com/elastic/elasticsearch-php/blob/master/README.md#contributing
Thanks for re-branch the PR to 7.x!

**Comment by williamdes** [comment]
> Thanks for re-branch the PR to 7.x!

I also can rebase if you want :)

Okay, so my changes will end up into master branch at some point ?
Do you merge 7.x into master ?

**Comment by ezimuel** [comment]
I'm rewriting elasticsearch-php 8.0.0 from scratch. I'll merge this PR to master. Thanks!

**Comment by williamdes** [comment]
> I'm rewriting elasticsearch-php 8.0.0 from scratch. I'll merge this PR to master. Thanks!

Oh okay ;)
I am impatient to see the merge ^^

Also I just had a look and https://github.com/elastic/elasticsearch-php/blob/master/.gitattributes seems not very in sync with the reality

**Comment by mfn** [comment]
> rewriting elasticsearch-php 8.0.0 from scratch

👀

**Comment by ezimuel** [comment]
@williamdes thanks a ton for this PR, the Doctum project looks awesome!

**Comment by williamdes** [comment]
> @williamdes thanks a ton for this PR, the Doctum project looks awesome!

Thanks for merging my work, can you change 
```
# Download the latest (5.1.x) release
curl -O https://doctum.long-term.support/releases/5.1/doctum.phar
curl -O https://doctum.long-term.support/releases/5.1/doctum.phar.sha256

sha256sum --strict --check doctum.phar.sha256
rm -f doctum.phar.sha256
# You can fetch the latest (5.1.x) version code here:
# https://doctum.long-term.support/releases/5.1/VERSION
```
by
```
# Download the latest (5.x.x) release
curl -O https://doctum.long-term.support/releases/5/doctum.phar
curl -O https://doctum.long-term.support/releases/5/doctum.phar.sha256

sha256sum --strict --check doctum.phar.sha256
rm -f doctum.phar.sha256
# You can fetch the latest (5.x.x) version code here:
# https://doctum.long-term.support/releases/5/VERSION
```

I just added the feature on the release script/process

**Pull request merged**
