### PR TITLE
Catch additional exceptions in the ping function for those who use mu…

### PR DESCRIPTION
**Pull request by josephtaylor-mn**
…ltiple nodes in their connection pool.

### CODE REVIEW

**Comment by josephtaylor-mn** [comment]
Does anyone have any insight into how to fix the issues being rose by the UnitTests? I am cannot find the point of failure and am wondering if it is perhaps not related to the code that I have altered.

**Comment by polyfractal** [comment]
I think this is an unrelated failure, but I'm on mobile boarding a plane so
wasn't able to look closely.

I'll take a closer look tomorrow and get back to you :)

Thanks for the PR btw!

**Comment by josephtaylor-mn** [comment]
Any news on the issues related to my PR not passing? Any help I can provide to get this merged in I would love to provide!!

Thanks!

**Comment by polyfractal** [comment]
Argh, sorry, i was travelling when I first saw this, then went on vacation a few days later.  And completely forgot. :(

Is there a reason you added the BadRequest400 exception?  400-level errors are returned when the client sends a badly constructed request (e.g. bad query syntax), which generally indicates the server is working just fine.

**Comment by polyfractal** [comment]
Re: those tests... I think that was transient test failures at the time (the runner was choking on certain responses due to some recent changes).  If you rebase onto the current master and re-push, we can check against the updated test code.

**Comment by polyfractal** [comment]
I'm going to modify this slightly and remove the BadRequest400, and merge.  Thanks!

**Comment by polyfractal** [comment]
Merged in: https://github.com/elastic/elasticsearch-php/commit/d857dd39523db62fd4307e5a3d902f6d35a8fc1e

**Pull request closed without merging**
