### PR TITLE
SearchHitIterators and SearchResponseIterator helpers revised with new version

### PR DESCRIPTION
**Pull request by hkulekci**
We have problems related to the PHPStan check. I had already mentioned in issue #1301

### CODE REVIEW

**Comment by ezimuel** [comment]
jenkins test this please

**Comment by hkulekci** [comment]
I think the tests will be broken because of phpstan. 🥹

**Comment by hkulekci** [comment]
I ignored the lines from PHPStan. But, the test is broken again because of another reason.

**Comment by hkulekci** [comment]
Ping @ezimuel

**Comment by hkulekci** [comment]
I could not understand the tests that gave errors. As I remember we got same error before. 

```
Unable to find image 'docker.elastic.co/elasticsearch/elasticsearch:8.8-SNAPSHOT' locally
docker: Error response from daemon: manifest for docker.elastic.co/elasticsearch/elasticsearch:8.8-SNAPSHOT not found: manifest unknown: manifest unknown.
```

**Comment by ezimuel** [comment]
Thanks @hkulekci fot the PR and sorry for the late reply.

**Comment by hkulekci** [comment]
Thanks for merging 🕺

**Pull request merged**
