### PR TITLE
Fixing script get and delete by removing lang from endpoint url

### PR DESCRIPTION
**Pull request by feydan**

### CODE REVIEW

**Comment by feydan** [comment]
Any update on this?

**Comment by jumandan** [comment]
I think that lang was copied from putScript. You should replace the doc in your commit.

https://github.com/elastic/elasticsearch-php/blob/master/docs/build/Elasticsearch/Client.asciidoc#Elasticsearch_ClientgetScript_getScript

**Comment by jumandan** [comment]
I create an issue [#824](https://github.com/elastic/elasticsearch-php/issues/824)

**Comment by luciansabo** [comment]
deleteScript() breaks in ES 6.4. Can this be integrated sooner?

**Comment by bogdanteleru** [comment]
@polyfractal https://github.com/elastic/elasticsearch-php/pull/814#issuecomment-463212555 👍

**Comment by radumaruntelu** [comment]
@polyfractal [Yes please!](https://github.com/elastic/elasticsearch-php/pull/814#issuecomment-463212555)

**Comment by emanuellainas** [comment]
@polyfractal [That](https://github.com/elastic/elasticsearch-php/pull/814#issuecomment-463212555) would be useful

**Comment by ciprianmardare** [comment]
@polyfractal very useful to have[this](https://github.com/elastic/elasticsearch-php/pull/814#issuecomment-463212555)

**Comment by idr0id** [comment]
@polyfractal any chance you can merge this soon?

**Comment by ezimuel** [comment]
Hi @feydan, @idr0id, @polyfractal and more. I'm the new maintainer of this library. I'll merge this PR soon. Thanks!

**Pull request merged**
