### PR TITLE
travis: drop PHP 7.0 from allowed failures, it passes well

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by polyfractal** [comment]
Ehh, I'd prefer to leave 7 as allowed-failure until it is released.  Just so there are fewer false alarms if something happens to break upstream while they are still working on 7.0.

**Comment by TomasVotruba** [comment]
Sure, I understand that.

**Comment by polyfractal** [comment]
Closing for now, but I believe 7.0 is just around the corner so we'll revisit it soon :)

**Comment by TomasVotruba** [comment]
Sure :)

**Comment by polyfractal** [comment]
Reopening now that PHP7 is out!

Not going to merge this quite yet, the 2.1 builds are broken atm due to some issues on our side (infra moved where snapshot builds are stored, need to sort that out first).

**Comment by TomasVotruba** [comment]
Good luck with fixing issues! Hope it goes well.

**Comment by polyfractal** [comment]
emot-toot

**Pull request merged**
