### PR TITLE
Fix `Response\Elasticsearch::offsetGet()` return type declaration

### LINKED ISSUE #1384: `Response\Elasticsearch::offsetGet()` return type declaration
### Summary of problem or feature request

There is a deprecation notice for the `Response\Elasticsearch::offsetGet()` related to the return type.

### Code snippet of problem

```
Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Elastic\Elasticsearch\Response\Elasticsearch" now to avoid errors or add an explicit @return annotation to suppress this message.
```

### System details

- PHP Version: 8.2
- ES-PHP client version: 7.17
- Elasticsearch version: 8.11

### PR DESCRIPTION
**Pull request by AnnaNtagiou**
Fixes #1384

### CODE REVIEW

**Comment by AnnaNtagiou** [comment]
@ezimuel, thanks for approving the workflow! The CI is green. The failure is not related to my changes.

**Comment by ruudk** [comment]
@ezimuel What's needed to get this merged and tagged? It would be great to silence the error reported by Symfony.

**Comment by AnnaNtagiou** [comment]
@ezimuel, you are probably very busy, but could you please let me know what needs to be done to move this PR forward? Thanks

**Comment by ezimuel** [comment]
@AnnaNtagiou sorry for the delay, just merged. Thanks!

**Comment by ruudk** [comment]
Thanks for merging it, will a tag follow soon as well? 😬

**Pull request merged**
