### PR TITLE
WIP: Update dev dependencies to specific version

### PR DESCRIPTION
**Pull request by mhujer**
From my point of view, it is best to use specific versions of dev-dependencies so that they won't break the build unexpectedly. So I changed them in the first commit.

In the other commits, I've updated the other dependencies.

---

Closes #680

### CODE REVIEW

**Comment by carusogabriel** [comment]
I'm closing #680, I couldn't figure out what went wrong :sweat_smile:

**Comment by mhujer** [comment]
@polyfractal I've rebased this on master and resolved the conflicts.

**Comment by ezimuel** [comment]
@mhujer I'm closing this because I don't think it's relevant anymore. Let me know if you want to discuss again and reopen it, thanks!

**Comment by mhujer** [comment]
@ezimuel Sure, it is an ancient one :-)

**Pull request closed without merging**
