### PR TITLE
Upgrade phpstan to 0.11.4

### PR DESCRIPTION
**Pull request by akondas**
Next step is bump level to 3 :fearful: :rocket:

### CODE REVIEW

**Comment by carusogabriel** [comment]
@akondas Hey, PHPStan 0.11 was released as well. Do you have plans to update this patch, or I can move this forward?

**Comment by akondas** [comment]
Updated :wink:

**Comment by thePanz** [comment]
In the meanwhile phpstan reached v0.11.4 :)

**Comment by akondas** [comment]
Welcome to open source :)

**Comment by ezimuel** [comment]
I updated the phpstan, phpcs and phpunit versions with commit https://github.com/elastic/elasticsearch-php/commit/aae4c90f7abd73f3a311854c7e502b0d6925b1b8.
I needed to change the requirement with `^0.9 || ^0.11`to be able to manage PHP 7.0+.
Thanks @akondas for your contribution.

**Pull request closed without merging**
