### PR TITLE
Syntax errors in Exception handling

### PR DESCRIPTION
**Pull request by abulhol**
Hi Zachary,
I managed to rollback my repo and create the pull request again. :-)

### CODE REVIEW

**Comment by polyfractal** [comment]
Great, thanks!  You beat me to it :)

It looks like you might have included another temp file (`"docs/configuration.asciidoc~"`) in the PR.  Would you be able to remove that, or do you want me to do it?

**Comment by abulhol** [comment]
I'll do that and create another pull request. :-)

**Comment by abulhol** [comment]
actually, now it looks ok. Git is not so easy if you don't use it all the time. ;-)

**Comment by polyfractal** [comment]
Git can indeed be tricky.  I use it every day and it still trips me up all the time.

Thanks!

**Pull request merged**
