### PR TITLE
Fall back for the empty array as new std class

### PR DESCRIPTION
**Pull request by vrkansagara**
fall back for the empty array as new std class

### CODE REVIEW

**Comment by polyfractal** [comment]
Actually, how about we just replace that `[]` with the stdClass so it is unambiguous which should be used?

**Comment by vrkansagara** [comment]
`stdClass` work in all the case with any library version and matter of the nosql I like object thinking not `[]`  thinking. and class and object I like most because It give flexibility to do more operation on it.

**Comment by polyfractal** [comment]
@vrkansagara Right, I meant instead of:

```php
 "match_all" => [] // or use new \stdClass() 
```
we just do:
```php
 "match_all" => new \stdClass() 
```

:)

**Comment by vrkansagara** [comment]
yes @polyfractal  that Want I like. using class notation is very much clear to understand.

**Comment by polyfractal** [comment]
Want to update your PR so it uses that notation, and I'll merge it?

**Comment by vrkansagara** [comment]
@polyfractal  done with PR updation. 👍

**Comment by polyfractal** [comment]
Thanks!  Merging :)

**Pull request merged**
