### PR TITLE
fix for invalid GET /_aliases route.

### PR DESCRIPTION
**Pull request by Artistan**
_aliases is no longer valid.
https://github.com/elastic/elasticsearch/search?utf8=%E2%9C%93&q=%2F_alias&type=

### CODE REVIEW

**Comment by Artistan** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-aliases.html

PUT and GET are now _alias not _aliases.  :)

**Comment by Artistan** [comment]
Looks like this should be done for all branches?
Not sure how it could have worked before.

**Comment by polyfractal** [comment]
Sorry for delay, was on holiday and then a week-long work trip.  I think all that needs to be done is remove [Indices/Aliases/Get](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Indices/Aliases/Get.php) as it is no longer valid.  

- [Indices/Aliases/Update](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Indices/Aliases/Update.php) is still a valid endpoint: [indices.update_aliases](https://github.com/elastic/elasticsearch/blob/6.x/rest-api-spec/src/main/resources/rest-api-spec/api/indices.update_aliases.json)
- Get/Put/Exists/Delete Alias endpoints are all available in the [Alias namespace](https://github.com/elastic/elasticsearch-php/tree/master/src/Elasticsearch/Endpoints/Indices/Alias) (note this is different from the [Aliases namespace](https://github.com/elastic/elasticsearch-php/tree/master/src/Elasticsearch/Endpoints/Indices/Aliases))

**Comment by Artistan** [comment]
looks right

**Comment by Artistan** [comment]
@polyfractal - I updated to remove the invalid endpoint

**Comment by Artistan** [comment]
closing and reopening to get the tests to run again...

**Comment by polyfractal** [comment]
Sorry, CI is/was kinda messed up.  Doing some PR merging right now to get CI back up and running.  If it's not fixed soonish I'll just pull this locally and run the tests myself.

**Comment by Artistan** [comment]
trying again.

**Comment by Artistan** [comment]
run tests

**Comment by Artistan** [comment]
@polyfractal - this is a critical fix IMHO since it is broken in the IndicesNamespace.
```php
// this call to the indices namespace is currently using an invalid Aliases route.
// it should be ... \Elasticsearch\Endpoints\Indices\Alias\Get, then it works fine.
$client->indices()->getAliases(['index' => "xyz_*"]);
```

**Comment by polyfractal** [comment]
So sorry this has lingered, I've been swamped with other work.  I think this LGTM and the tests are back to being reasonable.  Merging!

I'll be cutting a bugfix release imminently, few other critical things that need to go in with this.

**Pull request merged**
