### PR TITLE
Add getSource method to the README

### LINKED ISSUE #464: Add getSource() method to the README
I think a lot of people (like me) want to retrieve the `_source` directly, so I think that it would be nice to add the `getSource` method with a small explanation in the README.

### PR DESCRIPTION
**Pull request by YassineE**
Add getSource method to the README.

Fixes #464

### CODE REVIEW

**Comment by polyfractal** [comment]
Thanks!  Would you mind [Signing the CLA](https://www.elastic.co/contributor-agreement/) so that we can merge this?

**Comment by YassineE** [comment]
I already did it. How can I update the check ?

**Comment by polyfractal** [comment]
Ahh, oops.  My fault.  I checked the db manually, you're good to go.

There's not a clever way to tell the hooks to check again, I just forgot to run the manual check before commenting.  

Merging!

**Comment by YassineE** [comment]
Thanks ! 👍

**Pull request merged**
