### PR TITLE
Fix Travis build with Xdebug 3

### PR DESCRIPTION
**Pull request by derrabus**
This PR attempts to fix the Travis pipeline of the 6.x branch.

### CODE REVIEW

**Comment by ezimuel** [comment]
Thanks @derrabus for this PR but we are moving to Github Action. We already did for `master` and `7.x`. We need to change for `6.x` branch.

**Comment by derrabus** [comment]
Very well. Shall I backport the pipeline from master or is this already a work in progress?

**Comment by ezimuel** [comment]
You are more than welcome to send a PR for that. You can have a look at [.github](https://github.com/elastic/elasticsearch-php/tree/7.x/.github) folder in `7.x` branch.
Thanks again for your contribution!

**Comment by derrabus** [comment]
@ezimuel I tried to backport the GitHub actions workflow, but did not succeed. I invested a couple of hours today, but ultimately gave up because setting up the `util/elasticsearch` submodule did not work.

Then again, the Travis setup still works well enough and this PR would unblock the CI of the 6.x branch until someone more experienced with your test setup manages to migrate to GitHub actions.

**Comment by ezimuel** [comment]
@derrabus no problem, I'll fix the issue. Thanks again for your contribution.

**Pull request closed without merging**
