### PR TITLE
terminate_after not allowed in Count endpoint

### PR DESCRIPTION
**Pull request by brstgt**
Issue #632

### CODE REVIEW

**Comment by polyfractal** [comment]
<3  Thanks!

Would you mind [Signing the CLA](https://www.elastic.co/contributor-agreement/) so that I can merge this?

**Comment by polyfractal** [comment]
Oh, just saw your comment in #631.  If you don't want to sign the CLA that's fine, but I'll have to close this.  We only accept contributions from folks who have signed the CLA, no matter how small the contribution.

**Comment by brstgt** [comment]
I did but I do not know how to link it to my GitHub account.

2017-08-23 16:13 GMT+02:00 Zachary Tong <notifications@github.com>:

**Comment by brstgt** [comment]
FYI i use a different E-Mail on GitHub than my corporate one. Is this an
issue?

2017-08-23 16:16 GMT+02:00 benjamin roth <brstgt@gmail.com>:

**Comment by brstgt** [comment]
I signed the CLA. Once as individual and once as a corporate. Could you pls check?

**Comment by polyfractal** [comment]
I see you in the DB.  Thanks! :)

**Pull request merged**
