### PR TITLE
Update class Client.php call for case sensitive

### PR DESCRIPTION
**Pull request by txandy**
Update call method for case sensitive systems in ReIndex method.

### CODE REVIEW

**Comment by polyfractal** [comment]
The endpoint is `Reindex` with a lowercase 'i' though?  

https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Reindex.php#L14

**Comment by txandy** [comment]
Yes my bad. its solved in master branch, i use v2.2.1

**Comment by dalder** [comment]
true, seems to be solved in master. could this be fixed in branch 2.x too?

**Comment by polyfractal** [comment]
Agreed, we should backport this (sorry for delay, this slid through my inbox while traveling and I didn't notice)

Busy today, but tomorrow is my "PHP client day", so I'll backport then unless someone beats me to it with a PR :)

**Comment by dcarbone** [comment]
👍  for getting this into a 2.x release :)

**Pull request closed without merging**
