### PR TITLE
Add slices & wait_for_active_shards to UpdateByQuery whitelist

### PR DESCRIPTION
**Pull request by SosthenG**
As specified by the [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query-slice)

### CODE REVIEW

**Comment by thePanz** [comment]
Tests failures are not related to the changes introduced in this PR

**Comment by thePanz** [comment]
@polyfractal any news on this PR?

**Comment by thePanz** [comment]
@polyfractal any updates?

**Comment by polyfractal** [comment]
Hey @thePanz, @ezimuel has taken over maintaining this library (and has been much better about keeping it updated than I did!).  He's working on a backlog of issues right now but I'm sure this will get taken care of at some point in the near future.

Sorry for the delay!

**Comment by ezimuel** [comment]
@thePanz, @polyfractal the `slices` and `wait_for_active_shards` [has been added](https://github.com/elastic/elasticsearch-php/blob/v7.0.0/src/Elasticsearch/Endpoints/UpdateByQuery.php#L92-L96) in release 7.0.0.

**Comment by thePanz** [comment]
@ezimuel I see that you introduced those in https://github.com/elastic/elasticsearch-php/pull/897 (the diff is not clean, as it contains a huge mix of php-CS fixes, bc-break of supported PHP version and support for new API parameters).

In any case: those two parameters (slices and wait_for_active_shards) are available from ES 5.6: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-update-by-query.html#docs-update-by-query-slice and https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-update-by-query.html#_url_parameters_2

Does it means that the changes in the API parameters must be back-ported to the 5.6 branch?

**Comment by ezimuel** [comment]
ES 5.6 reaches EOL on 2019-03-11 and it's not maintained since 7.0.0. See [Elastic Product End of Life Dates](https://www.elastic.co/support/eol) for more information. 
This means, I can apply your PR to 6.0, 6.5.x and 6.7.x branches, for releasing 6.1.1, 6.5.1 and 6.7.2.
@thePanz are you using Elasticsearch 5, 6 or 7?

**Comment by thePanz** [comment]
@ezimuel I am still on ES 5.6.
So are you planning to drop support for the 5.x branch of this library?

**Comment by ezimuel** [comment]
@thePanz officially, I cannot fully support a library to connect to a server that is not supported anymore. That said, I would like to help all the users of this library. In this case, I'll release it for 5.x and 6.x.

**Comment by ezimuel** [comment]
@thePanz I just released elasticsearch-php [5.5.0](https://github.com/elastic/elasticsearch-php/releases/tag/v5.5.0) that fixes this issue and also #846.

**Comment by thePanz** [comment]
Cool! Thanks!

**Pull request closed without merging**
