### PR TITLE
Change setting

### PR DESCRIPTION
**Pull request by shfarzam**
Ther setting should be in an 'index' array field to work

### CODE REVIEW

**Comment by shfarzam** [comment]
the last version not working yet.

**Comment by ezimuel** [comment]
@shfarzam I just checked the example and it works fine. From the [documentation of Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/indices-create-index.html#create-index-settings):
> You do not have to explicitly specify `index` section inside the `settings` section

**Comment by shfarzam** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.1/indices-create-index.html#create-index-settings

**Comment by shfarzam** [comment]
Yes, thats true, when we want just define shards or replicas and for more config it's not working yet and the below commands work:
PUT twitter
{
    "settings" : {
        "index" : {
            "number_of_shards" : 3, 
            "number_of_replicas" : 2 
            "analyzer" : ......,
            "filter":.........
        }
    }
}

**Comment by shfarzam** [comment]
> @shfarzam see the second example in the page that you pointed out https://www.elastic.co/guide/en/elasticsearch/reference/7.1/indices-create-index.html#create-index-settings:
> 
> > **or more simplified**
> > ```
> > PUT twitter
> > {
> >    "settings" : {
> >        "number_of_shards" : 3,
> >        "number_of_replicas" : 2
> >    }
> > }
> > ```

**Pull request closed without merging**
