### PR TITLE
Allow installation of psr/http-message v2.0

### PR DESCRIPTION
**Pull request by gjuric**
Related to https://github.com/elastic/elastic-transport-php/pull/17 

I've signed the CLA in the meantime.

### CODE REVIEW

**Comment by gjuric** [comment]
The tests are failing because `php-http/client-common` in v2.7 dropped the dependency on `php-http/message-factory`.

See https://github.com/getsentry/sentry-php/issues/1533 for a similar case.

**Comment by ezimuel** [comment]
I fixed the issue and merged in main manually. Thanks!

**Comment by ezimuel** [comment]
@gjuric I had to remove the tag v8.8.1 because it has been released before the official schedule. The tag v8.8.1 will be re-created soon in a few days. Sorry for any inconvenience.

**Comment by gjuric** [comment]
Thanks for the heads up.

**Comment by ezimuel** [comment]
Released [v8.8.1](https://github.com/elastic/elasticsearch-php/releases/tag/v8.8.1) with #1313

**Pull request closed without merging**
