### PR TITLE
fix SearchResponseIterator scroll first page twice (#595)

### PR DESCRIPTION
**Pull request by safecat**
I have reproduced issue #595 on es5.5 and elasticsearch-php v5.3.2.
@biopowder create the issue but never submit a PR, the PR is totally based on his code in the issue description.
Hope you can merge this into branch 5.0 and check if there is same problem for other branch, thanks.

### CODE REVIEW

**Comment by safecat** [comment]
BTW, the CLA link in the PR description placeholder text is invalid(redirect to home page of elastic.co), I've already signed CLA at link(https://www.elastic.co/contributor-agreement) just 1 minutes ago.

**Comment by ezimuel** [comment]
Hi @safecat thanks for this PR. Can you show me where is the wrong CA link? I'll review this PR soon.

**Comment by safecat** [comment]
> Hi @safecat thanks for this PR. Can you show me where is the wrong CA link? I'll review this PR soon.

If someone tries to create a PR for this repo, the link is wrong in the default text in PR description text.

see:
2551554304131_ pic_hd

**Comment by ezimuel** [comment]
@safecat I fixed the CLA link with https://github.com/elastic/elasticsearch-php/commit/125e57e3b6b747b85fa43e3fddee5535f64bf4ef. Still working on the PR, sorry for the delay.

**Comment by ezimuel** [comment]
I'm closing this in favor of #871 with unit tests included. Thanks @safecat for your contribution!

**Pull request closed without merging**
