### PR TITLE
Update crud.asciidoc

### PR DESCRIPTION
**Pull request by wernight**
Remain consistent and fix the Bulk example code for #318

### CODE REVIEW

**Comment by rtuin** [comment]
This is almost correct. 

Your change will yield:
```json
{"_index": "indexname", "_type":"typename"}
```

Should be:
```json
{"index: {"_index": "indexname", "_type":"typename"}}
```

**Comment by wernight** [comment]
Thanks almost missed that.

**Comment by polyfractal** [comment]
Thanks!  Two things:

- Would you mind signing the [Elastic CLA](https://www.elastic.co/contributor-agreement/) so that I can merge this?

- Would you mind squashing this down to a single commit?  Not a huuuuge deal, but it'll make the history a tad cleaner.  If not, not a big deal :)

**Comment by wernight** [comment]
I'm however not yet very confident it fully works. It doesn't report errors but at the moment in my case it doesn't seems to popular the database correctly. I'm still investigating; may be a follow up PR.

**Comment by wernight** [comment]
Ok I found the example is correct but it should also check that `$response['errors']` is false:

````
if ($response['errors']) {
    throw new \Exception('Bulk operation failed.');
}
````

**Comment by polyfractal** [comment]
I'll give it a test on my end before I merge it too, just to help verify.  

One note:  errors are not necessarily a failure.  Elasticsearch can throw a Bulk Rejection exception, which basically means the server is at capacity and it refused to index some of the docs.  They aren't really errors, but more like "try again later" messages.

A proper, sophisticated bulk helper will queue up those rejected documents in a new request, wait a random 1-5s and then retry them...repeating the process until they have all been accepted.  Then resume the bulk process.

I'm not sure we want to include that level of detail in the example though?  It's meant to show how the bulk API works, not necessarily build a 100% robust bulk method?

**Comment by wernight** [comment]
I'd have in the second example (the more complete one):

````
if ($response['errors']) {
    // May be a real error, or a Bulk Rejection exception, which basically means the server
    // is at capacity and it refused to index some of the docs. Those aren't really errors,
    // but more like "try again later" messages.
    throw new \Exception('Bulk operation failed.');
}
````

**Comment by polyfractal** [comment]
++ that makes sense to me.

We can link to the "Bulk Rejections" portion of the guide here too, to provide further info:  https://www.elastic.co/guide/en/elasticsearch/guide/current/_monitoring_individual_nodes.html#_threadpool_section

**Comment by polyfractal** [comment]
Closing in favor of #386

**Pull request closed without merging**
