### PR TITLE
Fix SearchHitIterator key duplicates (#859)

### PR DESCRIPTION
**Pull request by safecat**

### CODE REVIEW

**Comment by ezimuel** [comment]
Hi @safecat, I'm the new maintainer of this library. I'll review this PR soon, thanks!

**Comment by ezimuel** [comment]
@safecat can you send this PR against master? I've unit tests in place for this PR, next time remember to include it in your PR. Thanks.

**Comment by elasticcla** [comment]
Hi @safecat, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch-php/pull/860.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by safecat** [comment]
Looks like I can not just change the target of this PR, it will contain many commit from master branch. So I created a new PR #872.
But, will this update be applied to branch 5.0?

I will create unit tests next time, thanks for the notice.

**Comment by ezimuel** [comment]
Thanks! I'm closing this in favor of #872.

**Pull request closed without merging**
