### PR TITLE
Fix the host path handling

### PR DESCRIPTION
**Pull request by elwinar**
Fix the bug on the host path handling. See https://github.com/elastic/elasticsearch-php/issues/356.

### CODE REVIEW

**Comment by polyfractal** [comment]
Awesome, thanks for sending this as a PR! Would you mind signing the [Elastic CLA](http://www.elasticsearch.org/contributor-agreement/) so I can merge it?

**Comment by elwinar** [comment]
On 2015-12-31 14:43, Zachary Tong wrote: 

> Awesome, thanks for sending this as a PR! Would you mind signing the Elastic CLA [1] so I can merge it? 
> 
> --
> Reply to this email directly or view it on GitHub [2].

Done. 
  

Links:
------
[1] http://www.elasticsearch.org/contributor-agreement/
[2]
https://github.com/elastic/elasticsearch-php/pull/359#issuecomment-168194666

**Comment by elwinar** [comment]
Any news on that ?

**Comment by polyfractal** [comment]
Whoops, sorry, slipped through my inbox.  Merging!

**Comment by elwinar** [comment]
Thank you. Any idea when it will be released ? For now I'm using my fork for local development, but I would like to use an upstream tagged version for my release.

**Comment by polyfractal** [comment]
I'll try to tag and release a version by the end of the day.  Few cosmetic things I'd like to finish first.

I'll ping this thread once it's released

**Comment by elwinar** [comment]
Fantastic. Thank you for your dedication.

**Comment by polyfractal** [comment]
Well, didn't get to the fixes today that I wanted, so went ahead and tagged/released so this would be live.

Tagged in `v2.1.4`!

**Pull request merged**
