### PR TITLE
Ping return param

### PR DESCRIPTION
**Pull request by phoenix-bjoern**
the phpdoc declaration has "array" as return value. In fact it is bool (true|false).

### CODE REVIEW

**Comment by polyfractal** [comment]
Thanks!  Can you sign the [Elastic CLA](http://www.elasticsearch.org/contributor-agreement/) so I can merge this?

**Comment by phoenix-bjoern** [comment]
@polyfractal I already have!?

**Comment by polyfractal** [comment]
Weird, sorry about that.  I just checked manually and you are definitely in the database, but our github integration tool didn't seem to agree.  Sorry about that!

**Comment by polyfractal** [comment]
Would you mind adjusting this PR to just include the fix to the ping?  It currently includes the commit which fixes the benchmarking too (which I just merged a second ago, btw)

**Comment by polyfractal** [comment]
Went ahead and cherry-picked the commit into master myself:  56a1107ef02de99a42f55ffa86e3565ce95bd742

Thanks!

**Pull request closed without merging**
