### PR TITLE
Readme: simplify install

### PR DESCRIPTION
**Pull request by TomasVotruba**
Composer will select last stable version by default.

### CODE REVIEW

**Comment by polyfractal** [comment]
I like this, especially since I want to start pushing people towards `v2.0` once it is out of beta.

Would you mind updating the docs to reflect this simplification too?

Also, would you mind signing the [Elasticsearch CLA](http://www.elasticsearch.org/contributor-agreement/) so I can merge this?

**Comment by TomasVotruba** [comment]
@polyfractal CLA signed.

Ad doc, seems like there's lot of [duplicated info](https://github.com/elastic/elasticsearch-php/blob/master/docs/installation.asciidoc#version-matrix) that can be found in [Readme](https://github.com/elastic/elasticsearch-php#version-matrix), which is outdated for this reason.

I'd recommend not to duplicate any content, and keep installation in Readme, since it's very easy step.

**Comment by polyfractal** [comment]
Yeah, I agree, it would be nice to only have one set of instructions instead of the same content duplicated.  Unfortunately, a fair number of people land on the documentation from search engines, and see the [site documentation](http://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_installation_2.html) before the project Readme.  It would be odd if they couldn't find the installation in the regular docs.

**Comment by TomasVotruba** [comment]
I agree. It's common practice to have link in Readme to full docs, e.g. [DoctrineBundle](https://github.com/doctrine/DoctrineBundle#documentation).

No duplication and everything could be found.

**Comment by TomasVotruba** [comment]
I'd suggest link Readme to [docs install](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_installation_2.html)

**Comment by polyfractal** [comment]
Circling back on this.  As much as I like DRY, I also like having installation + small code examples in the repo just so people can see a flavor.  It's only minor duplication with the docs.  And all the other ES repos do similar, so it is best if we stay semi-consistent with the other clients:

https://github.com/elastic/elasticsearch-py
https://github.com/elastic/elasticsearch-ruby
https://github.com/elastic/elasticsearch-js

If you don't want to update the docs, I'll merge this and do it myself.  Thanks! :)

**Comment by TomasVotruba** [comment]
> If you don't want to update the docs, I'll merge this and do it myself. Thanks! :)

That would be great, I'm out off time now. Thank you

**Comment by polyfractal** [comment]
Merged in https://github.com/elastic/elasticsearch-php/commit/dc8e072909af8ea34dfcb0bf01ee7d5d87469dea

**Pull request closed without merging**
